---
title: "Data by Commonwealth Election Division etc"
author: "Hugh Parsonage"
date: "17 July 2017"
output: html_document
---


```{r Region}
Region <- "STE"
```

```{r setup}
START <- Sys.time()
library(knitr)
data.kable <- function(DT) {
  current_knitr.kable.NA <- options("knitr.kable.NA")
  options(knitr.kable.NA = '...')
  on.exit(options(knitr.kable.NA = current_knitr.kable.NA))
  if (nrow(DT) > 50) {
    middle_row <- as.data.table(matrix(nrow = 1, ncol = ncol(DT)))
    setnames(middle_row, seq_along(middle_row), names(DT))
    DT_topn <- rbind(head(DT),
                     middle_row,
                     tail(DT))
    kable(DT_topn, format.args = list(big.mark = ","))
  } else {
    kable(DT, format.args = list(big.mark = ","))
  }
}
knitr::opts_knit$set(root.dir = "..")
knitr::opts_chunk$set(echo = TRUE, 
                      print_chunk = TRUE)
```

```{r loadPackages}
library(readxl)
library(testthat)
library(magrittr)
library(hutils)
library(data.table)
```

```{r Region_key}
Region_key <- 
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G01_AUS_', Region, '.csv')) %>%
  names %>%
  extract2(1)
```

```{r freadG}
#' @return Wide as-is data table of all tables.
freadG <- function(g) {
  stopifnot(length(g) == 1)
  g0 <- paste0(if (g < 10) "0", g)
  file_list <-
    list.files(path = file.path('./data-raw/data-packs/data/', Region, 'AUST'),
               # Files may be of the form ..G08_AUS.. or ..G09B_AUS..
               pattern = paste0('2016Census_G', g0, '[A-Z]?_AUS_', Region, '\\.csv$'),
               full.names = TRUE)
  if (length(file_list) > 1) {
    file_list %>%
    lapply(fread, key = Region_key) %>%
    Reduce(f = function(X, Y) X[Y])
  } else {
    fread(file = file_list[1])
  }
}
```

```{r grep-grepl-gsub}
# Performance
grep <- function(..., perl, fixed) base::grep(..., perl = missing(fixed), fixed = !missing(fixed))
grepl <- function(..., perl, fixed) base::grepl(..., perl = missing(fixed), fixed = !missing(fixed))
gsub <- function(..., perl, fixed) base::gsub(..., perl = missing(fixed), fixed = !missing(fixed))
```

```{r force_double}
force_double <- function(x) suppressWarnings(as.double(x))
```

```{r ngrep}
ngrep <- function(pattern, x, value = TRUE) {
  if (value) {
    x[!grepl(pattern, x)]
  } else {
    which(!grepl(pattern, x))
  }
}

expect_equal(ngrep("a", c("a", "ab", "b", "c")), c("b", "c"))
```

```{r Mop}
Mop <- function(DT, value.name = "persons", suborder = NULL) {
  stopifnot(value.name %in% names(DT))
  
  # Check for no duplicates, except for value.name
  if (anyDuplicated(DT, by = setdiff(names(DT), c(value.name, "variable")))) {
    print(duplicated_rows(DT, by = setdiff(names(DT), c(value.name, "variable"))))
    stop("Duplicated rows.")
  }
  
  out <- 
    DT %>%
    drop_col("variable") %>%
    setcolorder(sort(names(.))) %>%
    set_cols_first(Region_key) %>%
    setorderv(setdiff(names(.), value.name)) %>%
    set_cols_last(value.name) %>%
    .[]
  
  if ("CountryOfBirth" %in% names(DT)) {
    out[CountryOfBirth %pin% "Born elsewhere", CountryOfBirth := "(Born elsewhere)"]
  }
  
  for (j in names(DT)) {
   out[out[[j]] == "Other", (j) := "(Other)"]
  }
  
  # http://www.abs.gov.au/ausstats/abs@.nsf/0/1CD2B1952AFC5E7ACA257298000F2E76?OpenDocument
  if (value.name == "persons") {
    apparent_population <- sum(out[["persons"]])
    permitted_error <- switch(Region,
                              "SA1" = 1.0e6,
                              0.5e6)
    
    if (abs(apparent_population - 23401.9e3) > permitted_error) {
      if (apparent_population < 23401.9e3) {
        stop("Population undercounted: ", prettyNum(apparent_population, big.mark = ","),
             "\nShould you have used a different value.name?")
      } else {
        stop("Apparent population too high: ", prettyNum(apparent_population, big.mark = ","))
      }
    }
  }
    
  # Check for no duplicates, except for value.name
  if (anyDuplicated(out, by = setdiff(names(out), value.name))) {
    print(duplicated_rows(out, by = setdiff(names(out), value.name)))
    stop("Duplicated rows.")
  }
  if (!is.null(suborder)) {
    set_colsuborder(DT, suborder)
  }
  out[]
}
```

```{r Clear-tables}
# Ensure we are working with pristine tables
if (!isTRUE(getOption("knitr.in.progress"))) {
  AllTables <- Filter(function(x) is.data.table(get(x)), ls())
  if (length(AllTables) != 0) {
    menu_selection <- menu(c("Remove all tables.",
                             "Cancel."),
                           title = "Data tables detected. This script will save all tables in the workspace to the package. Remove current tables from workspace?")
  }
  
  if (exists("menu_selection")) {
    if (menu_selection %in% c(0, 2)) {
      stop("Operation cancelled.")
    } else {
      rm(list = AllTables)
    }
  }
}
```

```{r zero2NA}
zero2NA <- function(DT) {
  Classes <- vapply(DT, storage.mode, character(1))
  IntNoms <- names(Classes)[Classes == "integer"]
  for (j in which(Classes == "integer")) {
    set(DT, i = which(DT[[j]] == 0L), j = j, value = NA_integer_)
  }
  
  for (j in which(Classes == "double")) {
    set(DT, i = which(abs(DT[[j]]) < .Machine$double.eps), j = j, value = NA_real_)
  }
  DT
}

local({
  DT <- data.table(x = 1:5, y = c(0L, 1:4), z = c(-0.5, 0, 0.5, 1, 1.5),
                   ZZ = LETTERS[1:5])
  zero2NA(DT)
  
  expect_equal(DT[["x"]], 1:5)
  expect_equal(DT[["y"]], c(NA_integer_, 1:4))
  expect_equal(DT[["z"]], c(-0.5, NA_real_, 0.5, 1, 1.5))
  expect_equal(DT[["ZZ"]], LETTERS[1:5])
})
```

```{r CED_decoder}
CED_decoder <-
  read_excel("./data-raw/data-packs/Metadata/2016Census_geog_desc_1st_release.xlsx", 
             sheet = "2016_ASGS_Non-ABS_Structures") %>%
  setDT %>%
  .[ASGS_Structure == "CED"] %>%
  setnames("Census_Code_2016", Region_key) %>%
  setnames("Census_Name_2016", "Electoral_division") %>%
  .[, .SD, .SDcols =  c(Region_key, "Electoral_division")]
```

```{r extract_age}
extract_age <- function(variable, orderedFactor = TRUE) {
  out <- 
    variable %>%
    # Prepare:
    gsub("_yrs_ovr", "_ov", .) %>%
    gsub("([0-9]{2})_ov", "\\1ov", x = ., perl = TRUE) %>%
    gsub("^.*(_[0-9]{2}_[0-9]{2})_yrs?.*$", "\\1", x = .) %>%
    gsub("^.*85ov.*$", "_85ov", x = .) %>%
    # Extract
    gsub("^.*?_((?:[0-9]{1,2}(?![0-9]))(?:(?:_[0-9]{1,2}(?![0-9])))?(?:ov)?).*$", "\\1", ., perl = TRUE) %>%
    gsub("_", "-", ., fixed = TRUE) %>%
    gsub("_?ov", "+", ., perl = TRUE)
  
  # Has 'ov' in original and only numbers in out
  out <- dplyr::if_else(grepl("[^A-Za-z]ov[^A-Za-z]", variable, perl = TRUE) & grepl("^[0-9]+$", out),
                        paste0(out, "+"),
                        out)
  
  if (orderedFactor) {
    out <- factor(out, levels = unique(out), ordered = TRUE)
  }
  out
}

expect_equal(extract_age("Count_home_Census_Nt_0_14_yr", FALSE), "0-14")
expect_equal(extract_age("Age_0_4_yr_P", FALSE), "0-4")
expect_equal(extract_age("Age_psns_att_edu_inst_25_ov_P", FALSE), "25+")
expect_equal(extract_age("A_65_y_ov_Indig_stat_ns_P", FALSE), "65+")
expect_equal(extract_age("P_Hghst_yr_schl_ns_85_yrs_ovr", FALSE), "85+")
expect_equal(extract_age("M_1_149_15_19_yrs", FALSE), "15-19")
expect_equal(extract_age("M_1_149_85ov", FALSE), "85+")
```

```{r strip_age}
strip_age <- function(variable, orderedFactor = FALSE) {
  out <- 
    variable %>%
    # Prepare:
    gsub("([0-9]{2})_ov", "\\1ov", x = ., perl = TRUE) %>%
    # Extract
    gsub("(_[0-9]+(?:_[0-9]{1,2})?(?:ov)?)_yr", "", ., perl = TRUE)
  if (orderedFactor) {
    out <- factor(out, levels = unique(out), ordered = TRUE)
  }
  out
}

expect_equal(strip_age("P_15_19_yr_Marrd_reg_marrge"), "P_Marrd_reg_marrge")
```

### G01

```{r Region__Persons}
assign(paste0(Region, '__Persons'), { 
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G01_AUS_', Region, '.csv'),
        select = c(Region_key, "Tot_P_P")) %>%
  setnames("Tot_P_P", "persons")
})
```

```{r Region__Sex}
assign(paste0(Region, '__Sex'), { 
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G01_AUS_', Region, '.csv'),
        select = c(Region_key, "Tot_P_M", "Tot_P_F")) %>%
  melt.data.table(id.vars = Region_key,
                  variable.name = "Sex",
                  value.name = "persons") %>%
  .[, Sex := gsub("Tot_P_", "", Sex)] %>%
  .[]
})
```

```{r Region__Age}
assign(paste0(Region, '__Age'), {
   fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G01_AUS_', Region, '.csv')) %>%
  .[, .SD, .SDcols = c(Region_key, 
                       grep("^Age_[0-9].*P$", names(.), value = TRUE))] %>%
  melt.data.table(id.vars = Region_key,
                  variable.name = "Age",
                  value.name = "persons") %>%
  .[, Age := extract_age(Age)] %>%
  setorderv(setdiff(names(.), "persons")) %>%
  .[]
})
```

```{r Region__Age_Sex}
assign(paste0(Region, '__Age_Sex'), {
   fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G01_AUS_', Region, '.csv')) %>%
  .[, .SD, .SDcols = c(Region_key, 
                       grep("^Age_[0-9].*[MF]$", names(.), value = TRUE))] %>%
  melt.data.table(id.vars = Region_key,
                  
                  value.name = "persons") %>%
  .[, Age := extract_age(variable)] %>%
  .[, Sex := gsub("^.*([MF])$", "\\1", variable)] %>%
  .[, variable := NULL] %>%
  setorderv(setdiff(names(.), "persons")) %>%
  set_cols_last("persons") %>%
  .[]
})
```

```{r Region__HomeCensusNight}
assign(paste0(Region, '__HomeCensusNight'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G01_AUS_', Region, '.csv'), 
        select = c(Region_key, "Counted_Census_Night_home_P", "Count_Census_Nt_Ewhere_Aust_P")) %>%
  melt.data.table(id.vars = Region_key,
                  value.name = "persons") %>%
  .[, HomeCensusNight := grepl("home", variable)] %>%
  .[, .SD, .SDcols = c(Region_key, "HomeCensusNight", "persons")] %>%
  setorderv(setdiff(names(.), "persons")) %>%
  set_cols_last("persons") %>%
  .[]
})
```

```{r Region__HomeCensusNight_Sex}
assign(paste0(Region, '__HomeCensusNight_Sex'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G01_AUS_', Region, '.csv'), 
        select = c(Region_key,
                   "Counted_Census_Night_home_M", "Count_Census_Nt_Ewhere_Aust_M",
                   "Counted_Census_Night_home_F", "Count_Census_Nt_Ewhere_Aust_F")) %>%
  melt.data.table(id.vars = Region_key,
                  value.name = "persons") %>%
  
  .[, HomeCensusNight := grepl("home", variable)] %>%
  .[, Sex := gsub("^.*([MF])$", "\\1", variable, perl = TRUE)] %>%
  .[, .SD, .SDcols = c(Region_key, "HomeCensusNight", "Sex", "persons")] %>%
  setorderv(setdiff(names(.), "persons")) %>%
  set_cols_last("persons") %>%
  .[]
})
```

```{r Region__IndigenousStatus}
assign(paste0(Region, '__IndigenousStatus'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G01_AUS_', Region, '.csv'), 
        select = c(Region_key,
                   "Tot_P_P",
                   "Indigenous_psns_Aboriginal_P",
                   "Indig_psns_Torres_Strait_Is_P", 
                   "Indig_Bth_Abor_Torres_St_Is_P")) %>%
  .[, non_Indig := Tot_P_P - (Indigenous_psns_Aboriginal_P +
                                Indig_psns_Torres_Strait_Is_P +
                                Indig_Bth_Abor_Torres_St_Is_P)] %>%
  .[, Tot_P_P := NULL] %>%
  .[] %>%
  melt.data.table(id.vars = c(Region_key),
                  value.name = "persons") %>%
  .[, IndigenousStatus := "Non-indigenous"] %>%
  .[variable == "Indigenous_psns_Aboriginal_P",
    IndigenousStatus := "Aboriginal"] %>%
  .[variable == "Indig_Bth_Abor_Torres_St_Is_P",
    IndigenousStatus := "Both Aboriginal & Torres Strait Islander"] %>%
  .[variable == "Indig_psns_Torres_Strait_Is_P",
    IndigenousStatus := "Torres Strait Islander"] %>%
  .[, variable := NULL] %>%
  .[, IndigenousStatus := factor(IndigenousStatus, levels = unique(.$IndigenousStatus), ordered = TRUE)] %>%
  setorderv(setdiff(names(.), "persons")) %>%
  set_cols_last("persons") %>%
  .[]

})
```

```{r Region__BornAust}
assign(paste0(Region, '__BornAust'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G01_AUS_', Region, '.csv'), 
        select = c(Region_key, 
                   "Birthplace_Australia_P",
                   "Birthplace_Elsewhere_P")) %>%
  melt.data.table(id.vars = Region_key,
                  value.name = "persons") %>%
  .[variable == "Birthplace_Australia_P", BornAust := TRUE] %>%
  .[variable == "Birthplace_Elsewhere_P", BornAust := FALSE] %>%
  .[, variable := NULL] %>%
  setorderv(setdiff(names(.), "persons")) %>%
  set_cols_last("persons") %>%
  .[]
})
```

```{r Region__BornAust_Sex}
assign(paste0(Region, '__BornAust_Sex'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G01_AUS_', Region, '.csv'), 
        select = c(Region_key, 
                   "Birthplace_Australia_F", "Birthplace_Australia_M",
                   "Birthplace_Elsewhere_F", "Birthplace_Elsewhere_M")) %>%
  melt.data.table(id.vars = Region_key,
                  value.name = "persons") %>%
  .[variable %pin% "Birthplace_Australia", BornAust := TRUE] %>%
  .[variable %pin% "Birthplace_Elsewhere", BornAust := FALSE] %>%
  .[variable %pin% "F$", Sex := "F"] %>%
  .[variable %pin% "M$", Sex := "M"] %>%
  .[, variable := NULL] %>%
  setorderv(setdiff(names(.), "persons")) %>%
  set_cols_last("persons") %>%
  .[]
})
```

```{r Region__OnlyEnglishSpokenHome}
assign(paste0(Region, '__OnlyEnglishSpokenHome'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G01_AUS_', Region, '.csv'), 
        select = c(Region_key, 
                   "Lang_spoken_home_Eng_only_P",
                   "Lang_spoken_home_Oth_Lang_P")) %>%
  melt.data.table(id.vars = Region_key,
                  value.name = "persons") %>%
  .[variable == "Lang_spoken_home_Eng_only_P", OnlyEnglishSpokenHome := TRUE] %>%
  .[variable == "Lang_spoken_home_Oth_Lang_P", OnlyEnglishSpokenHome := FALSE] %>%
  .[, variable := NULL] %>%
  setorderv(setdiff(names(.), "persons")) %>%
  set_cols_last("persons") %>%
  .[]
})
```

```{r Region__OnlyEnglishSpokenHome_Sex}
assign(paste0(Region, '__OnlyEnglishSpokenHome_Sex'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G01_AUS_', Region, '.csv'), 
        select = c(Region_key, 
                   "Lang_spoken_home_Eng_only_F",
                   "Lang_spoken_home_Eng_only_M",
                   "Lang_spoken_home_Oth_Lang_F",
                   "Lang_spoken_home_Oth_Lang_M")) %>%
  melt.data.table(id.vars = Region_key, 
                  value.name = "persons") %>%
  .[variable %pin% "Lang_spoken_home_Eng_only", OnlyEnglishSpokenHome := TRUE] %>%
  .[variable %pin% "Lang_spoken_home_Oth_Lang", OnlyEnglishSpokenHome := FALSE] %>%
  .[variable %pin% "F$", Sex := "F"] %>%
  .[variable %pin% "M$", Sex := "M"] %>%
  .[, variable := NULL] %>%
  setorderv(setdiff(names(.), "persons")) %>%
  setcolorder(sort(names(.))) %>%
  set_cols_first(Region_key) %>%
  set_cols_last("persons") %>%
  .[]
})
```

```{r Region__AustCitizen}
assign(paste0(Region, '__AustCitizen'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G01_AUS_', Region, '.csv'),
        select = c(Region_key,
                   "Tot_P_P",
                   "Australian_citizen_P")) %>%
  .[, NAust := Tot_P_P - Australian_citizen_P] %>%
  .[, Tot_P_P := NULL] %>%
  melt.data.table(id.vars = Region_key) %>%
  .[, AustCitizen := TRUE] %>%
  .[variable == "NAust", AustCitizen := FALSE] %>%
  .[, variable := NULL] %>%
  setorderv(setdiff(names(.), "persons")) %>%
  setcolorder(sort(names(.))) %>%
  set_cols_first(Region_key) %>%
  set_cols_last("persons") %>%
  .[]
})
```


```{r Region__AustCitizen_Sex}
assign(paste0(Region, '__AustCitizen_Sex'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G01_AUS_', Region, '.csv'),
        select = c(Region_key,
                   "Tot_P_F",
                   "Australian_citizen_F",
                   "Tot_P_M",
                   "Australian_citizen_M")) %>%
  .[, NAust_F := Tot_P_F - Australian_citizen_F] %>%
  .[, NAust_M := Tot_P_M - Australian_citizen_M] %>%
  .[, Tot_P_F := NULL] %>%
  .[, Tot_P_M := NULL] %>%
  melt.data.table(id.vars = Region_key) %>%
  .[, AustCitizen := TRUE] %>%
  .[variable %pin% "NAust", AustCitizen := FALSE] %>%
  .[variable %pin% "F$", Sex := "F"] %>%
  .[variable %pin% "M$", Sex := "M"] %>%
  .[, variable := NULL] %>%
  setorderv(setdiff(names(.), "persons")) %>%
  setcolorder(sort(names(.))) %>%
  set_cols_first(Region_key) %>%
  set_cols_last("persons") %>%
  .[]
})
```

```{r Region__Age_students}
assign(paste0(Region, '__Age_students'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G01_AUS_', Region, '.csv'),
        select = c(Region_key,
                   "Age_psns_att_educ_inst_0_4_P",
                   "Age_psns_att_educ_inst_5_14_P", 
                   "Age_psns_att_edu_inst_15_19_P",
                   "Age_psns_att_edu_inst_20_24_P", 
                   "Age_psns_att_edu_inst_25_ov_P")) %>%
  melt.data.table(id.vars = Region_key,
                  variable.name = "Age",
                  value.name = "students") %>%
  .[, Age := extract_age(Age)] %>%
  .[] %>%
  setcolorder(sort(names(.))) %>%
  set_cols_first(Region_key) %>%
  setorderv(setdiff(names(.), c("persons"))) %>%
  set_cols_last("persons") %>%
  .[]
})
```

```{r Region__Age_Sex_students}
assign(paste0(Region, '__Age_Sex_students'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G01_AUS_', Region, '.csv'),
        select = c(Region_key,
                   "Age_psns_att_educ_inst_0_4_F",
                   "Age_psns_att_educ_inst_0_4_M",
                   "Age_psns_att_educ_inst_5_14_F", 
                   "Age_psns_att_educ_inst_5_14_M", 
                   "Age_psns_att_edu_inst_15_19_F",
                   "Age_psns_att_edu_inst_15_19_M",
                   "Age_psns_att_edu_inst_20_24_F", 
                   "Age_psns_att_edu_inst_20_24_M", 
                   "Age_psns_att_edu_inst_25_ov_F",
                   "Age_psns_att_edu_inst_25_ov_M")) %>%
  melt.data.table(id.vars = Region_key,
                  value.name = "students") %>%
  .[, Age := extract_age(variable)] %>%
  .[variable %pin% "F$", Sex := "F"] %>%
  .[variable %pin% "M$", Sex := "M"] %>%
  .[, variable := NULL] %>%
  setcolorder(sort(names(.))) %>%
  set_cols_first(Region_key) %>%
  setorderv(setdiff(names(.), c("persons"))) %>%
  set_cols_last("persons") %>%
  .[]
})
```

```{r Region__MaxSchoolingCompleted}
assign(paste0(Region, '__MaxSchoolingCompleted'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G01_AUS_', Region, '.csv')) %>%
  .[, .SD, .SDcols = c(Region_key, grep("High_yr_schl_comp_.*_P", names(.), value = TRUE))] %>%
  melt.data.table(id.vars = Region_key,
                  value.name = "persons") %>%
  .[, tmp := "Did not go to school"] %>%
  .[variable != "High_yr_schl_comp_D_n_g_sch_P",
    tmp := paste("Year", gsub("^.*Yr_([0-9]{1,2}).*$", "\\1", variable))] %>%
  .[, MaxSchoolingCompleted := factor(tmp, levels = rev(unique(.$tmp)), ordered = TRUE)] %>%
  .[, variable := NULL] %>%
  .[, tmp := NULL] %>%
  setcolorder(sort(names(.))) %>%
  set_cols_first(Region_key) %>%
  setorderv(setdiff(names(.), c("persons"))) %>%
  set_cols_last("persons") %>%
  .[]
})
```

```{r Region__MaxSchoolingCompleted_Sex}
assign(paste0(Region, '__MaxSchoolingCompleted_Sex'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G01_AUS_', Region, '.csv')) %>%
  .[, .SD, .SDcols = c(Region_key, grep("High_yr_schl_comp_.*_[MF]$", names(.), value = TRUE))] %>%
  melt.data.table(id.vars = Region_key,
                  value.name = "persons") %>%
  .[, tmp := "Did not go to school"] %>%
  .[variable %notin% c("High_yr_schl_comp_D_n_g_sch_F", "High_yr_schl_comp_D_n_g_sch_M"),
    tmp := paste("Year", gsub("^.*Yr_([0-9]{1,2}).*$", "\\1", variable))] %>%
  .[, MaxSchoolingCompleted := factor(tmp, levels = rev(unique(.$tmp)), ordered = TRUE)] %>%
  .[, Sex := gsub("^.*([MF])$", "\\1", variable)] %>%
  .[, variable := NULL] %>%
  .[, tmp := NULL] %>%
  setcolorder(sort(names(.))) %>%
  set_cols_first(Region_key) %>%
  setorderv(setdiff(names(.), c("persons"))) %>%
  set_cols_last("persons") %>%
  .[]
})
```

```{r Region__Dwelling}
assign(paste0(Region, '__Dwelling'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G01_AUS_', Region, '.csv'), 
        select = c(Region_key,
                   #"Count_psns_occ_priv_dwgs_M",
                   #"Count_psns_occ_priv_dwgs_F", 
                   "Count_psns_occ_priv_dwgs_P", 
                   #"Count_Persons_other_dwgs_M", 
                   #"Count_Persons_other_dwgs_F", 
                   "Count_Persons_other_dwgs_P")) %>%
    melt.data.table(id.vars = Region_key,
                    value.name = "persons") %>%
    .[, Dwelling := "Other"] %>%
    .[variable == "Count_psns_occ_priv_dwgs_P", Dwelling := "Private"] %>%
    Mop
})
```

```{r Region__Dwelling_Sex}
assign(paste0(Region, '__Dwelling_Sex'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G01_AUS_', Region, '.csv'), 
        select = c(Region_key,
                   "Count_psns_occ_priv_dwgs_M",
                   "Count_psns_occ_priv_dwgs_F", 
                   #"Count_psns_occ_priv_dwgs_P", 
                   "Count_Persons_other_dwgs_M", 
                   "Count_Persons_other_dwgs_F")) %>%
    melt.data.table(id.vars = Region_key,
                    value.name = "persons") %>%
    .[, Dwelling := "Other"] %>%
    .[variable %pin% "priv_dwgs", Dwelling := "Private"] %>%
    .[, Sex := gsub("^.*([MF])$", "\\1", variable)] %>%
    Mop
})
```

### G02
```{r Region__medianTotalPersonalIncome}
assign(paste0(Region, '__medianTotalPersonalIncome'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G02_AUS_', Region, '.csv')) %>%
    .[, .SD, .SDcols = c(Region_key, "Median_tot_prsnl_inc_weekly")] %>%
    setnames("Median_tot_prsnl_inc_weekly", "medianTotalPersonalIncome") %>%
    .[, medianTotalPersonalIncome := medianTotalPersonalIncome * 52L] %>%
    zero2NA %>%
    setcolorder(sort(names(.))) %>%
    set_cols_first(Region_key) %>%
    setorderv(setdiff(names(.), c("persons"))) %>%
    set_cols_last("persons") %>%
    .[]
})
```

```{r Region__medianMortgageRepayment}
assign(paste0(Region, '__medianMortgageRepayment'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G02_AUS_', Region, '.csv')) %>%
    .[, .SD, .SDcols = c(Region_key, "Median_mortgage_repay_monthly")] %>%
    setnames("Median_mortgage_repay_monthly", "medianMortgageRepayment") %>%
    .[, medianMortgageRepayment := medianMortgageRepayment * 12L] %>%
    zero2NA %>%
    setcolorder(sort(names(.))) %>%
    set_cols_first(Region_key) %>%
    setorderv(setdiff(names(.), c("persons"))) %>%
    set_cols_last("persons") %>%
    .[]
})
```

```{r Region__medianTotalHouseholdIncome}
assign(paste0(Region, '__medianTotalHouseholdIncome'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G02_AUS_', Region, '.csv')) %>%
    .[, .SD, .SDcols = c(Region_key, "Median_tot_hhd_inc_weekly")] %>%
    setnames("Median_tot_hhd_inc_weekly", "medianTotalHouseholdIncome") %>%
    .[, medianTotalHouseholdIncome := medianTotalHouseholdIncome * 52L] %>%
    zero2NA %>%
    setcolorder(sort(names(.))) %>%
    set_cols_first(Region_key) %>%
    setorderv(setdiff(names(.), c("persons"))) %>%
    set_cols_last("persons") %>%
    .[]
})
```

```{r Region__medianTotalFamilyIncome}
assign(paste0(Region, '__medianTotalFamilyIncome'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G02_AUS_', Region, '.csv')) %>%
    .[, .SD, .SDcols = c(Region_key, "Median_tot_fam_inc_weekly")] %>%
    setnames("Median_tot_fam_inc_weekly", "medianTotalFamilyIncome") %>%
    .[, medianTotalFamilyIncome := medianTotalFamilyIncome * 52L] %>%
    zero2NA %>%
    setcolorder(sort(names(.))) %>%
    set_cols_first(Region_key) %>%
    setorderv(setdiff(names(.), c("persons"))) %>%
    set_cols_last("persons") %>%
    .[]
})
```

```{r Region__medianRent}
assign(paste0(Region, '__medianRent'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G02_AUS_', Region, '.csv')) %>%
    .[, .SD, .SDcols = c(Region_key, "Median_rent_weekly")] %>%
    setnames("Median_rent_weekly", "medianRent") %>%
    .[, medianRent := medianRent * 52L] %>%
    zero2NA %>%
    setcolorder(sort(names(.))) %>%
    set_cols_first(Region_key) %>%
    setorderv(setdiff(names(.), c("persons"))) %>%
    set_cols_last("persons") %>%
    .[]
})
```

### G03

```{r Region__UsualResidence_Age}
assign(paste0(Region, '__UsualResidence_Age'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G03_AUS_', Region, '.csv')) %>%
  melt.data.table(id.vars = Region_key,
                  variable.factor = FALSE,
                  value.name = "persons") %>%
  .[!(variable %pin% "Tot")] %>%
  .[variable %pin% "(yr|85ov)$"] %>%
  .[, Age := extract_age(variable)] %>%
  .[, ResidenceVar := gsub("_([0-9]+(?:_[0-9]{2})?(?:ov)?)(?:_yr)?$", "", variable, perl = TRUE)] %>%

  .[ResidenceVar %pin% "Count_home?_Census_Nt",
    UsualResidence := "Home"] %>%

  .[ResidenceVar %pin% "VisDiff_SA2_",
    UsualResidence := paste("Visitor from", gsub("VisDiff_SA2_", "", ResidenceVar))] %>%
  .[ResidenceVar %pin% "VisSame",
    UsualResidence := "Visitor same SA2"] %>%
  .[, .SD, .SDcols = c(Region_key, "Age", "UsualResidence", "persons")] %>%
  setkeyv(c(Region_key, "Age", "UsualResidence")) %>%
  .[]
})
```

### G04

```{r Region__minAge}
assign(paste0(Region, '__minAge'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G04A_AUS_', Region, '.csv')) %>% 
  merge(fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G04B_AUS_', Region, '.csv')),
        by = Region_key) %>%
  .[, .SD, .SDcols = c(Region_key,
                       grep("yr_[0-9]{1,3}_(over_)?P$", names(.), value = TRUE),
                       "Age_yr_80_84_P",
                       "Age_yr_85_89_P",
                       "Age_yr_90_94_P",
                       "Age_yr_95_99_P",
                       "Age_yr_100_yr_over_P")] %>%
  melt.data.table(id.vars = Region_key,
                  variable.name = "minAge",
                  variable.factor = FALSE,
                  value.name = "persons") %>%
  .[, minAge := as.integer(gsub("Age_yr_([0-9]{1,3}).*P$", "\\1", minAge))] %>%
  setcolorder(sort(names(.))) %>%
  set_cols_first(Region_key) %>%
  setorderv(setdiff(names(.), c("persons"))) %>%
  set_cols_last("persons") %>%
  .[]
})
```

```{r Region__minAge_Sex}
assign(paste0(Region, '__minAge_Sex'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G04A_AUS_', Region, '.csv')) %>% 
  merge(fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G04B_AUS_', Region, '.csv')),
        by = Region_key) %>%
  .[, .SD, .SDcols = c(Region_key,
                       grep("yr_[0-9]{1,3}_(over_)?[MF]$", names(.), value = TRUE),
                       "Age_yr_80_84_F",
                       "Age_yr_80_84_M",
                       "Age_yr_85_89_F",
                       "Age_yr_90_94_M",
                       "Age_yr_95_99_F",
                       "Age_yr_95_99_M",
                       "Age_yr_100_yr_over_F",
                       "Age_yr_100_yr_over_M")] %>%
  melt.data.table(id.vars = Region_key,
                  variable.name = "variable",
                  variable.factor = FALSE,
                  value.name = "persons") %>%
  .[, minAge := as.integer(gsub("Age_yr_([0-9]{1,3}).*[MF]$", "\\1", variable))] %>%
  .[, Sex := gsub("Age_yr_(?:[0-9]{1,3}).*([MF])$", "\\1", variable, perl = TRUE)] %>%
  .[, variable := NULL] %>%
  setcolorder(sort(names(.))) %>%
  set_cols_first(Region_key) %>%
  setorderv(setdiff(names(.), c("persons"))) %>%
  set_cols_last("persons") %>%
  .[]
})
```

```{r Region__Age_MaritalStatus_Sex}
assign(paste0(Region, '__Age_MaritalStatus_Sex'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G05_AUS_', Region, '.csv')) %>% 
  .[,
    .SD,
    .SDcols = c(Region_key,
                grep("[MF]_[0-9]{2}(ov)?(_[0-9]{2}_yr)?_(Married|Separated|Divorced|Widowed)", names(.), value = TRUE))] %>%
  melt.data.table(id.vars = Region_key,
                  variable.factor = FALSE,
                  value.name = "persons") %>%
  .[, Age := extract_age(variable)] %>%
  .[, Sex := gsub("^([MF]).*$", "\\1", variable)] %>%
  .[, MaritalStatus := gsub("^.*(Married|Separated|Divorced|Widowed).*$", "\\1", variable, perl = TRUE)] %>%
  .[, variable := NULL] %>%
  setcolorder(sort(names(.))) %>%
  set_cols_first(Region_key) %>%
  setorderv(setdiff(names(.), c("persons"))) %>%
  set_cols_last("persons") %>%
  .[]

})
```

```{r Region__Age_MaritalStatus}
assign(paste0(Region, '__Age_MaritalStatus'), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G06_AUS_', Region, '.csv')) %>%
    .[, .SD, .SDcols = c(Region_key,
                         names(.)[grepl("^P", names(.)) & !grepl("Tot", names(.))])] %>%
    melt.data.table(id.vars = Region_key,
                    value.name = "adults") %>%
    .[, Age := extract_age(variable)] %>%
    .[, MaritalStatus := gsub("^.*(Marrd_reg_marrge|Married_de_facto|Not_married).*$", "\\1", variable)] %>%
    .[, MaritalStatus := gsub("_", " ", MaritalStatus)] %>%
    .[MaritalStatus == "Marrd reg marrge", Registered := TRUE] %>%
    .[MaritalStatus %pin% "de facto", Registered := FALSE] %>%
    .[MaritalStatus != "Not married", MaritalStatus := "Married"] %>%
    .[, variable := NULL] %>%
    setcolorder(sort(names(.))) %>%
    set_cols_first(Region_key) %>%
    setorderv(setdiff(names(.), c("adults"))) %>%
    set_cols_last("adults") %>%
    .[]
})
```

## G07

```{r CED__Age_Indigenous}
assign(paste0(Region, "__Age_Indigenous"), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G07_AUS_', Region, '.csv')) %>%
    .[, .SD, .SDcols = names(.)[nor(grepl("[MF]$", names(.)),
                                    grepl("Tot", names(.)))]] %>%
    melt.data.table(id.vars = Region_key,
                    value.name = "persons") %>%
    .[, Age := extract_age(variable)] %>%
    .[!grepl("_stat_ns", variable), Indigenous := !grepl("Non_Indig", variable)] %>%
    .[, variable := NULL] %>%
    setcolorder(sort(names(.))) %>%
    set_cols_first(Region_key) %>%
    setorderv(setdiff(names(.), c("persons"))) %>%
    set_cols_last("persons") %>%
    .[]
})
```

```{r CED__Age_Indigenous_Sex}
assign(paste0(Region, "__Age_Indigenous_Sex"), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G07_AUS_', Region, '.csv')) %>%
    .[, .SD, .SDcols = c(Region_key,
                         names(.)[and(grepl("[MF]$", names(.)),
                                    !grepl("Tot", names(.)))])] %>%
    melt.data.table(id.vars = Region_key,
                    value.name = "persons") %>%
    .[, Age := extract_age(variable)] %>%
    .[, Sex := gsub("^.*([MF])$", "\\1", variable)] %>%
    .[!grepl("_stat_ns", variable), Indigenous := !grepl("Non_Indig", variable)] %>%
    .[] %>%
    .[, variable := NULL] %>%
    setcolorder(sort(names(.))) %>%
    set_cols_first(Region_key) %>%
    setorderv(setdiff(names(.), c("persons"))) %>%
    set_cols_last("persons") %>%
    .[]
})
```

```{r Region__Ancestry}
assign(paste0(Region, "__Ancestry"), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G08_AUS_', Region, '.csv')) %>%
    .[, .SD, .SDcols = c(Region_key,
                         grep("Tot_Resp", names(.), value = TRUE))] %>%
    melt.data.table(id.vars = Region_key,
                    value.name = "responses") %>%
    .[variable != "Tot_P_Tot_Resp"] %>%
    .[!grepl("Ancestry_NS", variable),
      Ancestry := gsub("^([A-Z].*)_(BP|FO|MO).*$", "\\1", variable)] %>%
    .[Ancestry %pin% "Sth.Afri?can", Ancestry := "South African"] %>%
    .[, Ancestry := sub("_Tot_Resp", "", Ancestry)] %>%
    .[, Ancestry := gsub("_", " ", Ancestry)] %>%
    .[, Ancestry := gsub("Aust", "Australian", Ancestry)] %>%
    .[, Ancestry := gsub("Abor", "Aboriginal", Ancestry)] %>%
    .[, variable := NULL] %>%
    setcolorder(sort(names(.))) %>%
    set_cols_first(Region_key) %>%
    setorderv(setdiff(names(.), c("persons"))) %>%
    set_cols_last("persons") %>%
    .[]
})
```


```{r Region__Ancestry_FatherBornAus_MotherBornAus}
assign(paste0(Region, "__Ancestry_ParentsCountryOfBirth"), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G08_AUS_', Region, '.csv')) %>%
    .[, .SD, .SDcols = c(ngrep("Tot", names(.)))] %>%
    melt.data.table(id.vars = Region_key,
                    value.name = "responses") %>%
    .[!grepl("Ancestry_NS", variable),
      Ancestry := gsub("^([A-Z].*)_(BP|FO|MO).*$", "\\1", variable)] %>%
    .[Ancestry %pin% "Sth.Afri?can", Ancestry := "South African"] %>%
    # Join to obtain those with ancestry but whose parents were not
    # born overseas
    .[, Ancestry := sub("_Tot_Resp", "", Ancestry)] %>%
    .[, Ancestry := gsub("_", " ", Ancestry)] %>%
    .[, Ancestry := gsub("Aust", "Australian", Ancestry)] %>%
    .[, Ancestry := gsub("Abor", "Aboriginal", Ancestry)] %>%
    
    # Parents' country of birth
    .[variable %pin% "BP_B_Aus$", FatherBornAus := TRUE] %>%
    .[variable %pin% "BP_B_Aus$", MotherBornAus := TRUE] %>%
    .[variable %pin% "FO_B_OS$", FatherBornAus := FALSE] %>%
    .[variable %pin% "FO_B_OS$", MotherBornAus := TRUE] %>%
    .[variable %pin% "MO_B_OS$", FatherBornAus := TRUE] %>%
    .[variable %pin% "MO_B_OS$", MotherBornAus := FALSE] %>%
    .[variable %pin% "BP_B_OS$", FatherBornAus := FALSE] %>%
    .[variable %pin% "BP_B_OS$", MotherBornAus := FALSE] %>%
    .[] %>%
    Mop("responses")
})
```

## G09

```{r Region__CountryOfBirth}
assign(paste0(Region, "__CountryOfBirth"), {
  list.files(path = paste0('./data-raw/data-packs/data/', Region, '/AUST/'),
             pattern = paste0('2016Census_G09[A-Z]_AUS_', Region, '\\.csv$'),
             full.names = TRUE) %>%
    lapply(fread, key = Region_key) %>%
    Reduce(f = function(X, Y) X[Y]) %>%
    .[, .SD, .SDcols = c(Region_key, grep("^P.*(?<!(Tot_))Tot$", names(.), value = TRUE))] %>%
    melt.data.table(id.vars = Region_key,
                    value.name = "persons") %>%
    .[!grepl("COB_NS", variable), CountryOfBirth := gsub("^P_(.*)_Tot$", "\\1", variable)] %>%
    .[, CountryOfBirth := gsub("_", " ", CountryOfBirth)] %>%
    Mop
})
```

```{r Region__CountryOfBirth_Sex}
assign(paste0(Region, "__CountryOfBirth_Sex"), {
  list.files(path = paste0('./data-raw/data-packs/data/', Region, '/AUST/'),
             pattern = paste0('2016Census_G09[A-Z]_AUS_', Region, '\\.csv$'),
             full.names = TRUE) %>%
    lapply(fread, key = Region_key) %>%
    Reduce(f = function(X, Y) X[Y]) %>%
    .[, .SD, .SDcols = c(Region_key, grep("^[MF].*(?<!(Tot_))Tot$", names(.), value = TRUE))] %>%
    melt.data.table(id.vars = Region_key,
                    value.name = "persons") %>%
    .[!grepl("COB_NS", variable), CountryOfBirth := gsub("^[MF]_(.*)_Tot$", "\\1", variable)] %>%
    .[, CountryOfBirth := gsub("_", " ", CountryOfBirth)] %>%
    .[, CountryOfBirth := gsub("Born elsewhere", "(Born elsewhere)", CountryOfBirth, fixed = TRUE)] %>%
    .[, Sex := "M"] %>%
    .[grepl("^F", variable), Sex := "F"] %>%
    .[] %>%
    Mop
})
```

## G10

```{r Region__CountryOfBirth_YearOfArrival}
assign(paste0(Region, "__CountryOfBirth_YearOfArrival"), {
  list.files(path = paste0('./data-raw/data-packs/data/', Region, '/AUST/'),
             pattern = paste0('2016Census_G10[A-Z]_AUS_', Region, '\\.csv$'),
             full.names = TRUE) %>%
    lapply(fread, key = Region_key) %>%
    Reduce(f = function(X, Y) X[Y]) %>%
    .[, .SD, .SDcols = union(Region_key, ngrep("Tot", names(.), value = TRUE))] %>%
    melt.data.table(id.vars = Region_key,
                    value.name = "persons_born_overseas") %>%
    .[!grepl("NS$", variable, ignore.case = TRUE), YearOfArrival := gsub("^.*_([0-9]+)$", "\\1", variable)] %>%
    .[, CountryOfBirth := gsub("(_Be?fo?re)?_[0-9]+(_[0-9]+)?$", "", variable)] %>%
    # Negative lookbehind due to FYROM (Macedonia)
    .[, CountryOfBirth := gsub("(?<!(F))Ye?a?r.*arrival.ns$", "", CountryOfBirth, ignore.case = TRUE)] %>%
    .[, CountryOfBirth := trimws(gsub("_", " ", CountryOfBirth))] %>%
    .[CountryOfBirth %pin% "FYROM", CountryOfBirth := "FYROM"] %>%
    .[CountryOfBirth %pin% "China excl? SARs Tai?w", CountryOfBirth := "China excl SARs Taiwan"] %>%
    .[CountryOfBirth %pin% c("USA", "United States"), CountryOfBirth := "USA"] %>%
    .[CountryOfBirth %pin% "Korea", CountryOfBirth := "South Korea"] %>%
    .[CountryOfBirth %pin% "Ho?ng Ko?ng", CountryOfBirth := "Hong Kong"] %>%
    .[] %>%
    Mop("persons_born_overseas")
})
```

# G11

```{r Region__Age_EnglishProficiency_SpeaksEnglishOnly_YearOfArrival}
assign(paste0(Region, "__Age_EnglishProficiency_SpeaksEnglishOnly_YearOfArrival"), {
  list.files(path = paste0('./data-raw/data-packs/data/', Region, '/AUST/'),
             pattern = paste0('2016Census_G11[A-Z]_AUS_', Region, '\\.csv$'),
             full.names = TRUE) %>%
    lapply(fread, key = Region_key, na.strings = "..") %>%
    lapply(drop_empty_cols) %>%
    Reduce(f = function(X, Y) X[Y]) %>%
    .[, .SD, .SDcols = ngrep("^T|_T", names(.))] %>%
    melt.data.table(id.vars = Region_key, 
                    value.name = "persons_born_overseas") %>%
    .[, Age := gsub("^A([0-9]{1,2})_?([0-9]{2}|ov).*$", "\\1-\\2", variable)] %>%
    .[, Age := gsub("-ov", "+", Age, fixed = TRUE)] %>%
    .[, Age := factor(Age, levels = unique(.$Age), ordered = TRUE)] %>%
    .[grepl("SEO", variable), SpeaksEnglishOnly := TRUE] %>%
    .[grepl("SOLSE", variable), SpeaksEnglishOnly := FALSE] %>%
    .[grepl("VWW", variable), EnglishProficiency := "1Speaks English well or very well"] %>%
    .[grepl("NWNAA", variable), EnglishProficiency := "2Speaks English not well or not at all"] %>%
    .[order(EnglishProficiency)] %>%
    .[, EnglishProficiency := gsub("^[0-2]", "", EnglishProficiency)] %>%
    .[, EnglishProficiency := factor(EnglishProficiency, levels = unique(.$EnglishProficiency), ordered = TRUE)] %>%
    .[] %>%
    .[!grepl("YNS$", variable), YearOfArrival := 2000L + as.integer(gsub("^.*([0-9]{2})$", "\\1", variable))] %>%
    Mop("persons_born_overseas")
})
```

# G13 not used

```{r, eval=FALSE}
list.files(path = paste0('./data-raw/data-packs/data/', Region, '/AUST/'),
             pattern = paste0('2016Census_G12[A-Z]_AUS_', Region, '\\.csv$'),
             full.names = TRUE) %>%
    lapply(fread, key = Region_key, na.strings = "..") %>%
    lapply(drop_empty_cols) %>%
    Reduce(f = function(X, Y) X[Y]) %>%
    .[, .SD, .SDcols = ngrep("^T|_T", names(.))] %>%
    melt.data.table(id.vars = Region_key, 
                    value.name = "children_of_couple_families") %>%
    .[, Age := gsub("^A([0-9]{1,2})_?([0-9]{2}|ov).*$", "\\1-\\2", variable)] %>%
    .[, Age := gsub("-ov", "+", Age, fixed = TRUE)] %>%
    .[, Age := factor(Age, levels = unique(.$Age), ordered = TRUE)] %>%
    .[grepl("SEO", variable), SpeaksEnglishOnly := TRUE] %>%
    .[grepl("SOLSE", variable), SpeaksEnglishOnly := FALSE] %>%
    .[grepl("VWW", variable), EnglishProficiency := "1Speaks English well or very well"] %>%
    .[grepl("NWNAA", variable), EnglishProficiency := "2Speaks English not well or not at all"] %>%
    .[order(EnglishProficiency)] %>%
    .[, EnglishProficiency := gsub("^[0-2]", "", EnglishProficiency)] %>%
    .[, EnglishProficiency := factor(EnglishProficiency, levels = unique(.$EnglishProficiency), ordered = TRUE)] %>%
    .[] %>%
    .[!grepl("YNS$", variable), YearOfArrival := 2000L + as.integer(gsub("^.*([0-9]{2})$", "\\1", variable))] %>%
    Mop("children_of_couple_families")
```

```{r eval=FALSE}
list.files(path = paste0('./data-raw/data-packs/data/', Region, '/AUST/'),
             pattern = paste0('2016Census_G13[A-Z]_AUS_', Region, '\\.csv$'),
             full.names = TRUE) %>%
    lapply(fread, key = Region_key, na.strings = "..") %>%
    lapply(drop_empty_cols) %>%
    Reduce(f = function(X, Y) X[Y]) %>%
    .[, .SD, .SDcols = ngrep("^T|_T", names(.))] 

```

# G14

```{r Region__Religion_Sex}
assign(paste0(Region, "__Religion_Sex"), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G14_AUS_', Region, '.csv')) %>%
    .[, .SD, .SDcols = c(Region_key,
                         intersect(grep("[MF]$", names(.), value = TRUE),
                                   ngrep("Tot", names(.))))] %>%
    melt.data.table(id.vars = Region_key,
                    value.name = "persons") %>%
    .[, Sex := gsub("^.*([MF])$", "\\1", variable)] %>%
    .[!grepl("_ns_", variable), Religion := gsub("_[MF]", "", variable)] %>%
    .[Religion == "SB_OSB_NRA_NR", Religion := "No religion"] %>%
    .[Religion %pin% "Christ", Denomination := gsub("^Christ[a-z]+y_", "", Religion)] %>%
    .[Religion %pin% "Christ", Religion := "Christianity"] %>%
    .[Religion %enotin% c("Christianity", "Buddhism", "Hinduism", "Judaism", "Islam", "No religion"),
      Religion := "(Other)"] %>%
    .[variable %pin% "Prsby", Denomination := "Presbyterian Reformed"] %>%
    .[variable %pin% "Eastrn.Orthdox", Denomination := "Eastern Orthodox"] %>%
    .[variable %pin% "Orintal_Orthdx", Denomination := "Oriental Orthodox"] %>%
    .[variable %pin% "Sevnth.dy", Denomination := "Seventh Day Adventist"] %>%
    .[variable %pin% "Othr_Protestnt", Denomination := "Protestant (Other)"] %>%
    .[variable %pin% "Jehvahs_Witnses", Denomination := "Jehovah's Witnesses"] %>%
    .[variable %pin% "Othr_Christian", Denomination := "(Other)"] %>%
    .[variable %pin% "Sikhism", Denomination := "Sikhism"] %>%
    .[variable %pin% "Aust_Abor_Trad_Rel", Denomination := "Australian Aboriginal Traditional"] %>%
    .[variable %pin% "Othr_Reln_Other_reln_groups", Denomination := "(Other)"] %>%
    .[variable %pin% "SB_OSB_NRA_SB", Denomination := "Secular beliefs"] %>%
    .[variable %pin% "SB_OSB_NRA_OSB", Denomination := "Other spiritual beliefs"] %>%
    .[, Denomination := gsub("_", " ", Denomination)] %>%
    Mop(suborder = c("Religion", "Denomination"))
})
```

# G15

```{r Region__EduInstitutionType_Sex}
assign(paste0(Region, "__EduInstitutionType_Sex"), {
  freadG(15) %>%
     .[, .SD, .SDcols = names(.) %pin% c(Region_key, ".Tot.[MF]", "Pre_school_[MF]", "Type_educanl_institution_ns_[MF]")] %>%
    melt.data.table(id.vars = Region_key,
                    value.name = "students") %>%
    .[!(variable %pin% "Type_educanl_institution_ns_[MF]"), EduInstitutionType := gsub("_[MF]$", "", variable)] %>%
    .[variable %pin% "Pre.school", EduInstitutionType := "Pre-school"] %>%
    .[variable %pin% "Infants.Primary", EduInstitutionType := "Infants/Primary"] %>%
    .[variable %pin% "^Secondary", EduInstitutionType := "Secondary"] %>%
    .[variable %pin% "^Tec.Furt", EduInstitutionType := "Technical or Further Educational Institution"] %>%
    .[variable %pin% "^Uni", EduInstitutionType := "University or other tertiary"] %>%
    .[variable %pin% "^Oth", EduInstitutionType := "(Other)"] %>%
    #
    .[, Sex := gsub("^.*([MF])$", "\\1", variable)] %>%
    .[] %>%
    Mop("students")
})

test_that("Number of students approximately equal to Tot_P", {
  Tot_P <- freadG(15) %$% sum(Tot_P)
  expect_equal(get(paste0(Region, "__EduInstitutionType_Sex")) %$% sum(students), Tot_P, tol = 500)
})
```

```{r Region__AgedUnder25_EduInstitutionType_FullTime_SchoolSector_Sex}
assign(paste0(Region, "__AgedUnder25_EduInstitutionType_FullTime_SchoolSector_Sex"), {
  freadG(15) %>%
    drop_cols(grep("Tot", names(.), value = TRUE)) %>%
    drop_cols(grep("[P]$", names(.), value = TRUE)) %>%
    melt.data.table(id.vars = Region_key,
                    value.name = "students") %>%
    .[!(variable %pin% "Type_educanl_institution_ns_[MF]"), EduInstitutionType := gsub("_[MF]$", "", variable)] %>%
    .[variable %pin% "Pre.school", EduInstitutionType := "Pre-school"] %>%
    .[variable %pin% "Infa?nts.Prima?ry", EduInstitutionType := "Infants/Primary"] %>%
    .[variable %pin% "^Secondary", EduInstitutionType := "Secondary"] %>%
    .[variable %pin% "^Tec.Furt", EduInstitutionType := "Technical or Further Educational Institution"] %>%
    .[variable %pin% "^Uni", EduInstitutionType := "University or other tertiary"] %>%
    .[variable %pin% "^Oth", EduInstitutionType := "(Other)"] %>%
    #
    .[variable %pin% c("Primary", "^Secondary"), SchoolSector := gsub("^.*(Government|Catholic|Non_Govt).*$", "\\1", variable)] %>%
    #
    .[variable %pin% c("_Ft_(?!ns)", "_Pt_(?!ns)"), FullTime := variable %pin% "_Ft_"] %>%
    #
    .[variable %pin% c("25_ov", "15_24"), AgedUnder25 := variable %pin% "15_24"] %>%
    #
    .[, Sex := gsub("^.*([MF])$", "\\1", variable)] %>%
    .[] %>%
    Mop("students")
})

test_that("Number of students approximately equal to Tot_P", {
  Tot_P <- freadG(15) %$% sum(Tot_P)
  expect_equal(get(paste0(Region, "__EduInstitutionType_Sex")) %$% sum(students), Tot_P, tol = 500)
})
```

# G16
```{r Age_MaxSchooling_Sex}
freadG(16) %>%
  drop_cols(grep("Tot", names(.), value = TRUE)) %>%
  drop_cols(grep("^P_", names(.), value = TRUE)) %>%
  melt.data.table(id.vars = Region_key,
                  value.name = "adults") %>%
  .[, Age := extract_age(variable)] %>%
  .[, Sex := substr(variable, 0, 1)] %>%
  .[!grepl("schl_ns", variable), MaxSchooling := gsub("^[MF]_([A-Za-z0-9]+)_.*$", "\\1", variable)] %>%
  .[, MaxSchooling := gsub("Y([0-9]+)[eb]", "Year \\1", MaxSchooling)] %>%
  .[grepl("Y8b", variable), MaxSchooling := "Year 8 or below"] %>%
  .[grepl("DNGTS", variable), MaxSchooling := "Did not go to school"] %>%
  .[, MaxSchooling := factor(MaxSchooling, levels = rev(unique(.$MaxSchooling)), ordered = TRUE)] %>%
  .[] %>%
  Mop("adults")
```

# G17
```{r Age_TotPersonalIncome_Sex}
assign(paste0(Region, "__Age_TotPersonalIncome_Sex"), {
  
  freadG(17) %>%
    drop_cols(grep("^P_", names(.), value = TRUE)) %>%
    drop_cols(grep("Tot", names(.), value = TRUE)) %>%
    melt.data.table(id.vars = Region_key,
                    value.name = "adults") %>%
    .[, Sex := substr(variable, 0, 1)] %>%
    .[!grepl("PI_NS", variable), MinIncome := force_double(gsub("^[MF]_([0-9]+)_([0-9]+)_.*$", "\\1", variable))] %>%
    .[!grepl("PI_NS", variable), MaxIncome := force_double(gsub("^[MF]_([0-9]+)_([0-9]+)_.*$", "\\2", variable))] %>%
    .[grepl("Neg(tve)?_Nil_inco?me", variable), MinIncome := -Inf] %>%
    .[grepl("Neg(tve)?_Nil_inco?me", variable), MaxIncome := 0.0] %>%
    .[grepl("^[FM]_[0-9]+_more", variable), MaxIncome := Inf] %>%
    .[grepl("^[FM]_[0-9]+_more", variable), MinIncome := as.double(gsub("^[FM]_([0-9]+)_more.*", "\\1", variable))] %>%
    {
      for (j in c("MaxIncome", "MinIncome")) {
        # 149 -> 150 and annualize
        set(., j = j, value = 52.5 * round(.[[j]], -1))
      }
      .
    } %>%
    
    
    setnames(c("MaxIncome", "MinIncome"), 
             c("TotPersonalIncome.max", "TotPersonalIncome.min")) %>%
    
    .[, Age := extract_age(variable)] %>%
    .[] %>%
    Mop("adults", suborder = c("TotPersonalIncome.min", "TotPersonalIncome.max"))
})
```

# G18
```{r Age_NeedsAssistance_Sex}
assign(paste0(Region, "__Age_NeedsAssistance_Sex"), {
  freadG(18) %>%
    drop_cols(grep("Tot", names(.), value = TRUE)) %>%
    drop_cols(grep("^P", names(.), value = TRUE)) %>%
    melt.data.table(id.vars = Region_key,
                    value.name = "persons") %>%
    .[, Age := extract_age(variable)] %>%
    .[, Sex := substr(variable, 0, 1)] %>%
    .[!grepl("ns$", variable), NeedsAssistance := !grepl("No_need_for", variable)] %>%
    .[] %>%
    Mop
})
```

# G18

```{r Age_Volunteer_Sex}
assign(paste0(Region, "__Age_Volunteer_Sex"), {
  freadG(19) %>%
    drop_cols(grep("Tot", names(.), value = TRUE)) %>%
    drop_cols(grep("^P", names(.), value = TRUE)) %>%
    melt.data.table(id.vars = Region_key,
                    value.name = "adults") %>%
    .[, Age := extract_age(variable)] %>%
    .[, Sex := substr(variable, 0, 1)] %>%
    .[!grepl("ns$", variable), Volunteer := !grepl("N_A_Volunteer$", variable, ignore.case = TRUE)] %>%
    .[] %>%
    Mop("adults")
})
```

# G39

```{r Region__DwellingType_FamilyComposition_Storeys}
assign(paste0(Region, "__DwellingType_FamilyComposition_Storeys"), {
  fread(paste0('./data-raw/data-packs/data/', Region, '/AUST/2016Census_G39_AUS_', Region, '.csv')) %>%
    .[, .SD, .SDcols = c(ngrep("Tot", names(.)))] %>%
    melt.data.table(id.vars = Region_key,
                    value.name = "occupied_private_dwellings") %>%
    .[variable %pin% "^SH", DwellingType := "Separate house"] %>%
    .[variable %pin% "^SDRTHT", DwellingType := "Semi-detached row or terrace house, townhouse, etc"] %>%
    .[variable %pin% "^FoA", DwellingType := "Flat or apartment"] %>%
    .[variable %pin% "^OD", DwellingType := "Other dwelling"] %>%
    #
    .[variable %pin% "^OD_C_.", DwellingSubtype := "Caravan"] %>%
    .[variable %pin% "^OD_CH_", DwellingSubtype := "Cabin household"] %>%
    .[variable %pin% "^OD_Imp_home_T", DwellingSubtype := "Improvised home, tent sleepers"] %>%
    .[variable %pin% "^OD_HorF", DwellingSubtype := "House or flat attached to a shop, office, etc"] %>%
    .[variable %pin% "^OD_HorF", DwellingSubtype := "House or flat attached to a shop, office, etc"] %>%
    
    #
    .[variable %pin% "^SDRTHT_1_S", Storeys := "1"] %>%
    .[variable %pin% "^FoA_1_or_2", Storeys := "1 or 2"] %>%
    .[variable %pin% "^FoA_3SB", Storeys := "3"] %>%
    .[variable %pin% "^FoA_4moSB", Storeys := "4 or more"] %>%
    .[, Storeys := factor(Storeys, levels = c("1", "1 or 2", "3", "4 or more"), ordered = TRUE)] %>%
    
    .[variable %pin% "FHs_CF_no_C$", FamilyComposition := "Couple family with no children"] %>%
    .[variable %pin% "FHs_CF_C$", FamilyComposition := "Couple family with children"] %>%
    .[variable %pin% "FHs_OnePF$", FamilyComposition := "One parent family with children"] %>%
    .[variable %pin% "FHs_Oth_fam$", FamilyComposition := "Other family"] %>%
    .[variable %pin% "Lone_P_H$", FamilyComposition := "Lone-person household"] %>%
    .[variable %pin% "Group_H$", FamilyComposition := "Group household"] %>%
    .[, FamilyComposition := factor(FamilyComposition, levels = unique(.$FamilyComposition), ordered = TRUE)] %>%
    .[] %>%
    Mop("occupied_private_dwellings", suborder = c("DwellingType", "DwellingSubtype"))
})
```

```{r}
FINISH <- Sys.time()
```

```{r use_data, eval=dir.exists("data")}
# Print side-effect ok
stopifnot(dir.exists("data"))
ced_tbls <- tables()$NAME
for (tbl in ced_tbls) {
  save(list = tbl, file = file.path("data", paste0(tbl, ".rda")))
}
```
